### PR TITLE
Handle progress as string

### LINKED ISSUE #87: Handle progress as String instead of int
The Progress class should be the only one to convert String to int.
Otherwise Integer.parseInt has to be called by other classes, which causes unexpected errors due to the input being empty string or not an integer.

### PR DESCRIPTION
**Pull request by gekjunxu**
Fixes #87 

Fixed issue where progress prefix cannot be omitted, now it successfully defaults to 0 when omitted.

Currrently Progress has an overloaded constructor to create progress with 0, so current implementation is:

AddCommandParser.java - I check If prefix progress is omitted, default to 0, which calls ParserUtil#parseProgress, which then calls the overloaded constructor. 

Would it be better to omit the overloaded constructor, and just add a field in AddCommandParser to parse string "0"? What do yall think?

Edit: will add tests soon

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 1]
```diff
@@ -38,23 +38,28 @@ public AddCommand parse(String args) throws ParseException {
...
-        Progress progress = ParserUtil.parseProgress(progressValue);
 
+        Progress progress; // Initialise progress
+        if (arePrefixesPresent(argMultimap, PREFIX_PROGRESS)) {
+            // If progress prefix found, parse value accordingly.
+            progress = ParserUtil.parseProgress(argMultimap.getValue(PREFIX_PROGRESS).get());
+        } else {
+            // If prefix progress is omitted, default to 0.
+            progress = ParserUtil.parseProgress("");
+        }
```
Comment (ShiJianXi) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java:60]: Is it possible to refactor this into a single method, so that it can be more SLAP

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 2]
```diff
@@ -98,13 +98,16 @@ public static Project parseProject(String project) throws ParseException {
...
-        if (!Progress.isValidProgress(progress)) {
+    public static Progress parseProgress(String progress) throws ParseException {
+        if (progress.trim().isEmpty()) {
+            // Call overloaded constructor with progress 0,
+            // if progress prefix not in command
+            return new Progress();
+        } else if (!Progress.isValidProgress(progress)) {
             throw new ParseException(Progress.MESSAGE_CONSTRAINTS);
         }
         return new Progress(progress);
```
Comment (ShiJianXi) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:113]: Personally, I feel it would be better if we just called new Progress(0) instead of having a overloaded constructor, this can help reduce unnecessary code and unnecessary test also.

**Comment by weiwong834** [comment]
LGTM

**Comment by gekjunxu** [comment]
fixes #94
